import { afterEach, describe, expect, it } from 'bun:test';
import { chmod, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  generateArtifact,
  getGenerationProviderStatus,
} from '../../../packages/serve/src/lib/server/generation-provider.js';

const tempDirectories: string[] = [];

async function tempDirectory(prefix: string): Promise<string> {
  const directory = await mkdtemp(join(tmpdir(), prefix));
  tempDirectories.push(directory);
  return directory;
}

async function fakeCommand(
  directory: string,
  name: 'codex' | 'claude',
  body: string
): Promise<void> {
  const executable = join(directory, name);
  await writeFile(executable, `#!/bin/sh\nset -eu\n${body}\n`, 'utf8');
  await chmod(executable, 0o755);
}

function isolatedEnvironment(binDirectory: string, homeDirectory: string): NodeJS.ProcessEnv {
  return {
    PATH: binDirectory,
    HOME: homeDirectory,
    CODEX_HOME: join(homeDirectory, '.codex'),
    LANG: 'C.UTF-8',
  };
}

const codexGenerator = String.raw`
output=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    -o|--output-last-message)
      output="$2"
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done
prompt="$(/bin/cat)"
case "$prompt" in
  *"agent markdown file"*)
    /bin/cat > "$output" <<'EOF'
---
name: codex-agent
description: Generated by Codex
model: gpt-test-frontier
model_reasoning_effort: high
domain: universal
tools:
  - Read
  - Grep
  - Glob
---

# Codex Agent
EOF
    ;;
  *"skill SKILL.md file"*)
    /bin/cat > "$output" <<'EOF'
---
name: codex-skill
description: Generated by Codex
scope: core
---

## Instructions

Use Codex.
EOF
    ;;
  *"guide README.md file"*)
    printf '# Codex Guide\n\nGenerated by Codex.\n' > "$output"
    ;;
  *)
    echo "unexpected prompt" >&2
    exit 64
    ;;
esac`;

afterEach(async () => {
  await Promise.all(
    tempDirectories.splice(0).map((directory) => rm(directory, { recursive: true, force: true }))
  );
});

describe('generation provider selection', () => {
  it('uses Codex as the only required provider for agent, skill, and guide generation', async () => {
    const root = await tempDirectory('omcodex-serve-provider-root-');
    const bin = await tempDirectory('omcodex serve provider bin ');
    await fakeCommand(bin, 'codex', codexGenerator);
    const env = isolatedEnvironment(bin, root);

    expect(await getGenerationProviderStatus({ env })).toEqual({
      codexAvailable: true,
      claudeCompatibilityAvailable: false,
      preferredMode: 'codex',
    });

    const agent = await generateArtifact('agent', 'Create an agent', root, {
      env,
      keywordFallback: () => 'keyword-agent',
    });
    const skill = await generateArtifact('skill', 'Create a skill', root, {
      env,
      keywordFallback: () => 'keyword-skill',
    });
    const guide = await generateArtifact('guide', 'Create a guide', root, {
      env,
      keywordFallback: () => 'keyword-guide',
    });

    expect(agent.mode).toBe('codex');
    expect(agent.content).toContain('model_reasoning_effort: high');
    expect(skill.mode).toBe('codex');
    expect(skill.content).toContain('name: codex-skill');
    expect(guide.mode).toBe('codex');
    expect(guide.content).toContain('# Codex Guide');
    expect(agent.diagnostics).toEqual([]);
  });

  it('prefers Codex when both Codex and the Claude compatibility CLI are present', async () => {
    const root = await tempDirectory('omcodex-serve-provider-root-');
    const bin = await tempDirectory('omcodex-serve-provider-bin-');
    const claudeMarker = join(root, 'claude-called');
    await fakeCommand(bin, 'codex', codexGenerator);
    await fakeCommand(bin, 'claude', `printf called > '${claudeMarker}'\nexit 91`);

    const result = await generateArtifact('guide', 'Create a guide', root, {
      env: isolatedEnvironment(bin, root),
      keywordFallback: () => 'keyword-guide',
    });

    expect(result.mode).toBe('codex');
    expect(result.content).toContain('# Codex Guide');
    expect(await Bun.file(claudeMarker).exists()).toBe(false);
  });

  it('falls back from a failed Codex invocation to the explicit Claude compatibility provider', async () => {
    const root = await tempDirectory('omcodex-serve-provider-root-');
    const bin = await tempDirectory('omcodex-serve-provider-bin-');
    const claudeArgs = join(root, 'claude-args.txt');
    const injectionTarget = join(root, 'PWNED');
    await fakeCommand(bin, 'codex', 'echo "codex unavailable" >&2\nexit 17');
    await fakeCommand(
      bin,
      'claude',
      `printf '%s\\n' "$@" > '${claudeArgs}'\n/bin/cat <<'EOF'\n# Claude compatibility output\nEOF`
    );

    const result = await generateArtifact(
      'guide',
      `Never execute $(touch ${injectionTarget})`,
      root,
      {
        env: isolatedEnvironment(bin, root),
        keywordFallback: () => 'keyword-guide',
      }
    );

    expect(result.mode).toBe('claude-compat');
    expect(result.content).toBe('# Claude compatibility output');
    expect(result.diagnostics.join('\n')).toContain('Codex CLI failed');
    expect(await readFile(claudeArgs, 'utf8')).toContain(
      `Never execute $(touch ${injectionTarget})`
    );
    expect(await Bun.file(injectionTarget).exists()).toBe(false);
  });

  it('reports both CLI failures before using the keyword fallback', async () => {
    const root = await tempDirectory('omcodex-serve-provider-root-');
    const bin = await tempDirectory('omcodex-serve-provider-bin-');
    await fakeCommand(bin, 'codex', 'echo "codex diagnostic" >&2\nexit 21');
    await fakeCommand(bin, 'claude', 'echo "claude diagnostic" >&2\nexit 22');

    const result = await generateArtifact('skill', 'Create a skill', root, {
      env: isolatedEnvironment(bin, root),
      keywordFallback: () => 'keyword-skill',
    });

    expect(result).toMatchObject({
      mode: 'keyword-fallback',
      content: 'keyword-skill',
    });
    expect(result.diagnostics.join('\n')).toContain('Codex CLI failed');
    expect(result.diagnostics.join('\n')).toContain('Claude compatibility CLI failed');
    expect(result.diagnostics.join('\n')).toContain('codex diagnostic');
    expect(result.diagnostics.join('\n')).toContain('claude diagnostic');
  });

  it('rejects an oversized Codex last-message file before reading it into memory', async () => {
    const root = await tempDirectory('omcodex-serve-provider-root-');
    const bin = await tempDirectory('omcodex-serve-provider-bin-');
    await fakeCommand(
      bin,
      'codex',
      `
output=""
while [ "$#" -gt 0 ]; do
  case "$1" in
    -o|--output-last-message)
      output="$2"
      shift 2
      ;;
    *)
      shift
      ;;
  esac
done
/bin/dd if=/dev/zero of="$output" bs=1048577 count=1 2>/dev/null`
    );

    const result = await generateArtifact('guide', 'Create a guide', root, {
      env: isolatedEnvironment(bin, root),
      keywordFallback: () => 'keyword-guide',
    });

    expect(result).toMatchObject({
      mode: 'keyword-fallback',
      provider: null,
      content: 'keyword-guide',
    });
    expect(result.diagnostics.join('\n')).toContain('Codex output file exceeded 1048576 bytes');
  });

  it('uses keyword mode without pretending that a CLI attempt occurred when no provider exists', async () => {
    const root = await tempDirectory('omcodex-serve-provider-root-');
    const bin = await tempDirectory('omcodex-serve-provider-bin-');

    const result = await generateArtifact('agent', 'Create an agent', root, {
      env: isolatedEnvironment(bin, root),
      keywordFallback: () => 'keyword-agent',
    });

    expect(result).toEqual({
      mode: 'keyword',
      provider: null,
      content: 'keyword-agent',
      diagnostics: ['Codex CLI not found', 'Claude compatibility CLI not found'],
    });
  });
});
