/**
 * Compile managed Claude-compatible Markdown agents into Codex native TOML roles.
 *
 * Markdown remains the upstream/source artifact. This module is the provider boundary:
 * it validates the source schema, drops Claude-only tool metadata, resolves model lanes,
 * emits deterministic TOML, and safely synchronizes only generated TOML files.
 */

import { accessSync, constants as fsConstants, readFileSync, realpathSync } from 'node:fs';
import { lstat, readdir, readFile } from 'node:fs/promises';
import { homedir } from 'node:os';
import { basename, delimiter, dirname, isAbsolute, join, resolve } from 'node:path';
import { parse as parseYaml } from 'yaml';
import {
  deleteFile,
  prevalidateSafeWritePath,
  validateSafeDeleteFilePath,
  writeTextFile,
} from '../utils/fs.js';
import { type AgentDomain, shouldInstallAgent } from './scope-filter.js';

export const NATIVE_AGENT_GENERATED_HEADER =
  '# Generated by oh-my-customcodex from a managed Markdown agent. Do not edit.\n';

const AGENT_NAME_PATTERN = /^[A-Za-z0-9][A-Za-z0-9_-]*$/;
const SKILL_NAME_PATTERN = /^[A-Za-z0-9][A-Za-z0-9:_-]*$/;
const MODEL_VALUE_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._/-]*$/;
const TOML_BARE_KEY_PATTERN = /^[A-Za-z0-9_-]+$/;
const PROJECT_SKILL_PATH_PATTERN =
  /^\.\.\/\.\.\/\.agents\/skills\/[A-Za-z0-9][A-Za-z0-9:_-]*\/SKILL\.md$/;
const NATIVE_AGENT_TOP_LEVEL_STRING_FIELDS = new Set([
  'name',
  'description',
  'developer_instructions',
  'model',
  'model_reasoning_effort',
  'sandbox_mode',
]);

const AGENT_DOMAINS = new Set<AgentDomain>([
  'backend',
  'frontend',
  'data-engineering',
  'devops',
  'universal',
]);

export const NATIVE_REASONING_EFFORTS = [
  'none',
  'minimal',
  'low',
  'medium',
  'high',
  'xhigh',
  'ultra',
  'max',
] as const;
export type NativeReasoningEffort = (typeof NATIVE_REASONING_EFFORTS)[number];

export const NATIVE_MODEL_LANES = ['inherit', 'frontier', 'spark'] as const;
export type NativeModelLane = (typeof NATIVE_MODEL_LANES)[number];

const REASONING_EFFORTS = new Set<NativeReasoningEffort>(NATIVE_REASONING_EFFORTS);
const MODEL_LANES = new Set<NativeModelLane>(NATIVE_MODEL_LANES);
const SAFE_SANDBOX_MODES = new Set<NativeSandboxMode>(['read-only', 'workspace-write']);
const WRITE_CAPABLE_CLAUDE_TOOLS = new Set(['Bash', 'Edit', 'NotebookEdit', 'Write']);

const MCP_SCALAR_STRING_FIELDS = ['bearer_token_env_var', 'command', 'cwd', 'url'] as const;
const MCP_BOOLEAN_FIELDS = ['enabled', 'required'] as const;
const MCP_NUMBER_FIELDS = ['startup_timeout_sec', 'tool_timeout_sec'] as const;
const MCP_STRING_ARRAY_FIELDS = ['args', 'disabled_tools', 'enabled_tools', 'env_vars'] as const;
const MCP_STRING_MAP_FIELDS = ['env', 'env_http_headers', 'http_headers'] as const;
const MCP_STDIO_ONLY_FIELDS = new Set(['args', 'cwd', 'env', 'env_vars']);
const MCP_HTTP_ONLY_FIELDS = new Set(['bearer_token_env_var', 'env_http_headers', 'http_headers']);
const MCP_SUPPORTED_FIELDS = new Set<string>([
  ...MCP_SCALAR_STRING_FIELDS,
  ...MCP_BOOLEAN_FIELDS,
  ...MCP_NUMBER_FIELDS,
  ...MCP_STRING_ARRAY_FIELDS,
  ...MCP_STRING_MAP_FIELDS,
]);

export type NativeSandboxMode = 'read-only' | 'workspace-write';

export interface NativeSkillConfig {
  path: string;
  enabled: boolean;
}

export interface NativeMcpServerConfig {
  bearer_token_env_var?: string;
  command?: string;
  cwd?: string;
  url?: string;
  enabled?: boolean;
  required?: boolean;
  startup_timeout_sec?: number;
  tool_timeout_sec?: number;
  args?: string[];
  disabled_tools?: string[];
  enabled_tools?: string[];
  env_vars?: string[];
  env?: Record<string, string>;
  env_http_headers?: Record<string, string>;
  http_headers?: Record<string, string>;
}

export interface NativeAgentConfig {
  name: string;
  description: string;
  developer_instructions: string;
  model?: string;
  model_reasoning_effort?: NativeReasoningEffort;
  sandbox_mode?: NativeSandboxMode;
  mcp_servers?: Record<string, NativeMcpServerConfig>;
  skills?: { config: NativeSkillConfig[] };
}

export interface ModelLaneConfig {
  frontier?: string;
  spark?: string;
}

export interface CompileMarkdownAgentOptions {
  /** Source filename, used to enforce a stable one-source/one-role mapping. */
  sourceFilename?: string;
  /** Explicit model lanes. Environment overrides are used when omitted. */
  modelLanes?: ModelLaneConfig;
}

export interface CompiledNativeAgent {
  sourceName: string;
  filename: string;
  domain: AgentDomain;
  config: NativeAgentConfig;
  toml: string;
}

export interface NativeAgentListMetadata {
  name: string;
  description: string;
}

export interface NativeAgentDetailMetadata extends NativeAgentListMetadata {
  developerInstructions: string;
  model?: string;
  modelReasoningEffort?: NativeReasoningEffort;
  sandboxMode?: NativeSandboxMode;
  skills: string[];
}

export interface SyncNativeAgentsOptions {
  sourceDir: string;
  destinationDir: string;
  targetRoot: string;
  domain?: string;
  modelLanes?: ModelLaneConfig;
}

export interface SyncNativeAgentsResult {
  compiled: CompiledNativeAgent[];
  written: string[];
  unchanged: string[];
  removed: string[];
  preserved: string[];
  filtered: string[];
}

interface ParsedMarkdownAgent {
  sourceName: string;
  description: string;
  developerInstructions: string;
  domain: AgentDomain;
  metadata: Record<string, unknown>;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function requireNonEmptyString(value: unknown, field: string): string {
  if (typeof value !== 'string' || value.trim() === '') {
    throw new Error(`Agent frontmatter requires a non-empty ${field}`);
  }
  return value.trim();
}

function normalizeBody(body: string): string {
  return body.replace(/\r\n?/g, '\n').trim();
}

function parseAgentDomain(value: unknown): AgentDomain {
  if (value === undefined) return 'universal';
  if (typeof value !== 'string' || !AGENT_DOMAINS.has(value as AgentDomain)) {
    throw new Error(`Invalid agent domain: ${String(value)}`);
  }
  return value as AgentDomain;
}

function parseMarkdownAgent(markdown: string): ParsedMarkdownAgent {
  const cleaned = markdown.replace(/^\uFEFF/, '');
  const match = cleaned.match(/^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)([\s\S]*)$/);
  if (!match) {
    throw new Error('Agent source must contain YAML frontmatter followed by Markdown instructions');
  }

  let parsed: unknown;
  try {
    parsed = parseYaml(match[1]);
  } catch (error) {
    throw new Error(`Invalid agent YAML frontmatter: ${String(error)}`);
  }
  if (!isRecord(parsed)) {
    throw new Error('Agent YAML frontmatter must be an object');
  }

  const sourceName = requireNonEmptyString(parsed.name, 'name');
  if (!AGENT_NAME_PATTERN.test(sourceName)) {
    throw new Error(`Invalid agent name: ${sourceName}`);
  }

  const description = requireNonEmptyString(parsed.description, 'description');
  const developerInstructions = normalizeBody(match[2]);
  if (!developerInstructions) {
    throw new Error(`Agent ${sourceName} requires Markdown developer instructions`);
  }

  return {
    sourceName,
    description,
    developerInstructions,
    domain: parseAgentDomain(parsed.domain),
    metadata: parsed,
  };
}

function validateModelValue(model: string, field = 'model'): string {
  const normalized = model.trim();
  if (!MODEL_VALUE_PATTERN.test(normalized)) {
    throw new Error(`Invalid ${field}: ${model}`);
  }
  return normalized;
}

function readOmxConfig(codexHome: string): Record<string, unknown> | undefined {
  try {
    const parsed = JSON.parse(readFileSync(join(codexHome, '.omx-config.json'), 'utf8')) as unknown;
    return isRecord(parsed) ? parsed : undefined;
  } catch {
    return undefined;
  }
}

function readConfiguredString(record: unknown, key: string): string | undefined {
  if (!isRecord(record)) return undefined;
  const value = record[key];
  return typeof value === 'string' && value.trim() ? value.trim() : undefined;
}

function readCodexRootModel(codexHome: string): string | undefined {
  try {
    const config = readFileSync(join(codexHome, 'config.toml'), 'utf8').replace(/^\uFEFF/, '');
    for (const line of config.split(/\r?\n/)) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      if (trimmed.startsWith('[')) break;
      const assignment = trimmed.match(/^model\s*=\s*(.+)$/);
      if (assignment) return parseTomlStringLiteral(assignment[1], 'config model').trim();
    }
  } catch {
    // Match OMX config resolution: malformed or missing config falls back to defaults.
  }
  return undefined;
}

function omxExecutableNames(environment: NodeJS.ProcessEnv): string[] {
  if (process.platform !== 'win32') return ['omx'];
  const extensions = (environment.PATHEXT ?? '.COM;.EXE;.BAT;.CMD')
    .split(';')
    .map((extension) => extension.trim().toLowerCase())
    .filter(Boolean);
  return ['omx', ...extensions.map((extension) => `omx${extension}`)];
}

function omxEntrypointsFromExecutable(executable: string): string[] {
  const entrypoints = new Set<string>();
  try {
    accessSync(executable, fsConstants.X_OK);
    entrypoints.add(realpathSync(executable));
  } catch {
    return [];
  }

  try {
    const shim = readFileSync(executable, 'utf8').slice(0, 16_384);
    const entrypointPattern = /(['"])([^'"\r\n]*[\\/]dist[\\/]cli[\\/]omx\.js)\1/g;
    for (const match of shim.matchAll(entrypointPattern)) {
      const path = match[2];
      entrypoints.add(realpathSync(isAbsolute(path) ? path : resolve(dirname(executable), path)));
    }
  } catch {
    // A native/symlinked executable is sufficient; wrapper inspection is best-effort only.
  }
  return [...entrypoints];
}

function installedOmxPackageRoots(environment: NodeJS.ProcessEnv): string[] {
  const pathValue = environment.PATH ?? environment.Path;
  if (!pathValue) return [];

  const roots = new Set<string>();
  for (const directory of pathValue
    .split(delimiter)
    .map((entry) => entry.trim())
    .filter(Boolean)) {
    for (const name of omxExecutableNames(environment)) {
      for (const entrypoint of omxEntrypointsFromExecutable(join(directory, name))) {
        const normalized = entrypoint.replaceAll('\\', '/');
        if (!normalized.endsWith('/dist/cli/omx.js')) continue;
        roots.add(dirname(dirname(dirname(entrypoint))));
      }
    }
  }
  return [...roots];
}

let installedOmxSparkDefaultCache:
  | { discoveryKey: string; sparkModel: string | undefined }
  | undefined;

function installedOmxDiscoveryKey(environment: NodeJS.ProcessEnv): string {
  return [
    process.platform,
    environment.PATH ?? environment.Path ?? '',
    environment.PATHEXT ?? '',
  ].join('\0');
}

function readInstalledOmxSparkDefault(environment: NodeJS.ProcessEnv): string | undefined {
  const discoveryKey = installedOmxDiscoveryKey(environment);
  if (installedOmxSparkDefaultCache?.discoveryKey === discoveryKey) {
    return installedOmxSparkDefaultCache.sparkModel;
  }

  let sparkModel: string | undefined;
  for (const packageRoot of installedOmxPackageRoots(environment)) {
    try {
      const packageJson = JSON.parse(readFileSync(join(packageRoot, 'package.json'), 'utf8')) as {
        name?: unknown;
      };
      if (packageJson.name !== 'oh-my-codex') continue;

      const contract = readFileSync(join(packageRoot, 'dist', 'config', 'models.js'), 'utf8');
      const declaration = contract.match(
        /\bexport\s+const\s+DEFAULT_SPARK_MODEL\s*=\s*(['"])([^'"\r\n]+)\1\s*;/
      );
      if (!declaration) continue;
      sparkModel = validateModelValue(declaration[2], 'installed OMX DEFAULT_SPARK_MODEL');
      break;
    } catch {
      // Ignore incomplete or non-standard installations and continue to the next PATH entry.
    }
  }
  installedOmxSparkDefaultCache = { discoveryKey, sparkModel };
  return sparkModel;
}

/** Resolve the same frontier/spark precedence as the installed OMX model contract. */
export function getConfiguredModelLanes(
  environment: NodeJS.ProcessEnv = process.env,
  codexHomeOverride?: string
): ModelLaneConfig {
  const codexHome =
    codexHomeOverride?.trim() || environment.CODEX_HOME?.trim() || join(homedir(), '.codex');
  const omxConfig = readOmxConfig(codexHome);
  const configEnvironment = isRecord(omxConfig?.env) ? omxConfig.env : undefined;
  const configuredModels = isRecord(omxConfig?.models) ? omxConfig.models : undefined;

  const frontier =
    readCodexRootModel(codexHome) ||
    environment.OMX_DEFAULT_FRONTIER_MODEL?.trim() ||
    readConfiguredString(configEnvironment, 'OMX_DEFAULT_FRONTIER_MODEL');
  const spark =
    environment.OMX_DEFAULT_SPARK_MODEL?.trim() ||
    environment.OMX_SPARK_MODEL?.trim() ||
    readConfiguredString(configEnvironment, 'OMX_DEFAULT_SPARK_MODEL') ||
    readConfiguredString(configEnvironment, 'OMX_SPARK_MODEL') ||
    readConfiguredString(configuredModels, 'team_low_complexity') ||
    readConfiguredString(configuredModels, 'team-low-complexity') ||
    readConfiguredString(configuredModels, 'teamLowComplexity') ||
    readInstalledOmxSparkDefault(environment);
  return {
    frontier: frontier ? validateModelValue(frontier, 'frontier model lane') : undefined,
    spark: spark ? validateModelValue(spark, 'spark model lane') : undefined,
  };
}

function hasMetadataValue(value: unknown): boolean {
  return value !== undefined && value !== null && value !== '';
}

function resolveNativeModelLane(value: unknown, lanes: ModelLaneConfig): string | undefined {
  if (typeof value !== 'string' || !MODEL_LANES.has(value as NativeModelLane)) {
    throw new Error(`Invalid model_lane: ${String(value)}`);
  }
  if (value === 'inherit') return undefined;
  const resolved = lanes[value as Exclude<NativeModelLane, 'inherit'>];
  if (value === 'spark' && !resolved) {
    throw new Error(
      'Spark model lane is unavailable: configure OMX_DEFAULT_SPARK_MODEL or install a discoverable OMX model contract'
    );
  }
  return resolved ? validateModelValue(resolved, `${value} model lane`) : undefined;
}

function resolveCompatibilityModel(value: unknown, lanes: ModelLaneConfig): string | undefined {
  if (!hasMetadataValue(value)) return undefined;
  if (typeof value !== 'string') {
    throw new Error('Agent model must be a string');
  }

  const normalized = value.trim();
  if (normalized === 'inherit') return undefined;
  if (normalized === 'sonnet' || normalized === 'opus') {
    return lanes.frontier ? validateModelValue(lanes.frontier, 'frontier model lane') : undefined;
  }
  if (normalized === 'haiku') {
    if (!lanes.spark) {
      throw new Error(
        'Spark model lane is unavailable: configure OMX_DEFAULT_SPARK_MODEL or install a discoverable OMX model contract'
      );
    }
    return validateModelValue(lanes.spark, 'spark model lane');
  }
  return validateModelValue(normalized);
}

function resolveModel(
  metadata: Record<string, unknown>,
  modelLanes?: ModelLaneConfig
): string | undefined {
  const model = metadata.model;
  const modelLane = metadata.model_lane;
  const hasModel = hasMetadataValue(model);
  const hasModelLane = hasMetadataValue(modelLane);
  if (hasModel && hasModelLane) {
    throw new Error('Agent model and model_lane conflict');
  }

  const lanes = modelLanes ?? getConfiguredModelLanes();
  return hasModelLane
    ? resolveNativeModelLane(modelLane, lanes)
    : resolveCompatibilityModel(model, lanes);
}

function resolveReasoningEffort(
  metadata: Record<string, unknown>
): NativeReasoningEffort | undefined {
  const legacyEffort = metadata.effort;
  const nativeEffort = metadata.model_reasoning_effort;
  if (legacyEffort !== undefined && nativeEffort !== undefined && legacyEffort !== nativeEffort) {
    throw new Error('Agent effort and model_reasoning_effort conflict');
  }

  const effort = nativeEffort ?? legacyEffort;
  if (effort === undefined || effort === null || effort === '') return undefined;
  if (typeof effort !== 'string' || !REASONING_EFFORTS.has(effort as NativeReasoningEffort)) {
    throw new Error(`Invalid model_reasoning_effort: ${String(effort)}`);
  }
  return effort as NativeReasoningEffort;
}

function stringArray(value: unknown, field: string): string[] {
  if (!Array.isArray(value) || value.some((entry) => typeof entry !== 'string' || !entry.trim())) {
    throw new Error(`${field} must be an array of non-empty strings`);
  }
  return value.map((entry) => (entry as string).trim());
}

function effectiveClaudeTools(metadata: Record<string, unknown>): string[] {
  if (metadata.tools === undefined) return [];
  const tools = stringArray(metadata.tools, 'tools');
  const disallowed =
    metadata.disallowedTools === undefined
      ? new Set<string>()
      : new Set(stringArray(metadata.disallowedTools, 'disallowedTools'));
  return tools.filter((tool) => !disallowed.has(tool));
}

function resolveSandboxMode(metadata: Record<string, unknown>): NativeSandboxMode | undefined {
  const explicitSandbox = metadata.sandbox_mode;
  if (explicitSandbox !== undefined) {
    if (explicitSandbox === 'danger-full-access') {
      throw new Error('danger-full-access is not allowed for compiled managed agents');
    }
    if (
      typeof explicitSandbox !== 'string' ||
      !SAFE_SANDBOX_MODES.has(explicitSandbox as NativeSandboxMode)
    ) {
      throw new Error(`Invalid sandbox_mode: ${String(explicitSandbox)}`);
    }
    return explicitSandbox as NativeSandboxMode;
  }

  const permissionMode = metadata.permissionMode;
  if (permissionMode === undefined) return undefined;
  if (permissionMode !== 'default' && permissionMode !== 'bypassPermissions') {
    throw new Error(`Unsupported Claude permissionMode: ${String(permissionMode)}`);
  }

  const canWrite = effectiveClaudeTools(metadata).some((tool) =>
    WRITE_CAPABLE_CLAUDE_TOOLS.has(tool)
  );
  return canWrite ? 'workspace-write' : 'read-only';
}

function normalizeSkillName(name: string): string {
  if (!SKILL_NAME_PATTERN.test(name)) {
    throw new Error(`Invalid skill name: ${name}`);
  }
  for (const prefix of ['omcustomcodex:', 'omcodex:']) {
    if (name.startsWith(prefix)) return name.slice(prefix.length);
  }
  return name;
}

function validateSkillPath(path: string): string {
  const normalized = path.replaceAll('\\', '/');
  if (!PROJECT_SKILL_PATH_PATTERN.test(normalized)) {
    throw new Error(`Invalid project skill path: ${path}`);
  }
  return normalized;
}

function resolveSkillConfig(value: unknown): NativeSkillConfig[] | undefined {
  if (value === undefined || value === null) return undefined;
  if (Array.isArray(value)) {
    const names = stringArray(value, 'skills');
    const seen = new Set<string>();
    return names.map((name) => {
      const normalizedName = normalizeSkillName(name);
      const path = `../../.agents/skills/${normalizedName}/SKILL.md`;
      if (seen.has(path)) throw new Error(`Duplicate skill config: ${path}`);
      seen.add(path);
      return { path, enabled: true };
    });
  }

  if (!isRecord(value) || !Array.isArray(value.config)) {
    throw new Error('skills must be a string array or a native skills.config object');
  }
  const seen = new Set<string>();
  return value.config.map((entry, index) => {
    if (!isRecord(entry)) throw new Error(`skills.config[${index}] must be an object`);
    const path = validateSkillPath(
      requireNonEmptyString(entry.path, `skills.config[${index}].path`)
    );
    const enabled = entry.enabled ?? true;
    if (typeof enabled !== 'boolean') {
      throw new Error(`skills.config[${index}].enabled must be a boolean`);
    }
    if (seen.has(path)) throw new Error(`Duplicate skill config: ${path}`);
    seen.add(path);
    return { path, enabled };
  });
}

function requireBoolean(value: unknown, field: string): boolean {
  if (typeof value !== 'boolean') throw new Error(`${field} must be a boolean`);
  return value;
}

function requirePositiveNumber(value: unknown, field: string): number {
  if (typeof value !== 'number' || !Number.isFinite(value) || value <= 0) {
    throw new Error(`${field} must be a positive number`);
  }
  return value;
}

function requireStringMap(value: unknown, field: string): Record<string, string> {
  if (!isRecord(value)) throw new Error(`${field} must be a string map`);
  return Object.fromEntries(
    Object.entries(value)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([key, entry]) => {
        if (typeof entry !== 'string') throw new Error(`${field}.${key} must be a string`);
        return [key, entry];
      })
  );
}

function assignMcpStringFields(
  server: NativeMcpServerConfig,
  value: Record<string, unknown>,
  name: string
): void {
  for (const field of MCP_SCALAR_STRING_FIELDS) {
    if (value[field] !== undefined) {
      server[field] = requireNonEmptyString(value[field], `mcp_servers.${name}.${field}`);
    }
  }
}

function assignMcpBooleanFields(
  server: NativeMcpServerConfig,
  value: Record<string, unknown>,
  name: string
): void {
  for (const field of MCP_BOOLEAN_FIELDS) {
    if (value[field] !== undefined) {
      server[field] = requireBoolean(value[field], `mcp_servers.${name}.${field}`);
    }
  }
}

function assignMcpNumberFields(
  server: NativeMcpServerConfig,
  value: Record<string, unknown>,
  name: string
): void {
  for (const field of MCP_NUMBER_FIELDS) {
    if (value[field] !== undefined) {
      server[field] = requirePositiveNumber(value[field], `mcp_servers.${name}.${field}`);
    }
  }
}

function assignMcpArrayFields(
  server: NativeMcpServerConfig,
  value: Record<string, unknown>,
  name: string
): void {
  for (const field of MCP_STRING_ARRAY_FIELDS) {
    if (value[field] !== undefined) {
      server[field] = stringArray(value[field], `mcp_servers.${name}.${field}`);
    }
  }
}

function assignMcpMapFields(
  server: NativeMcpServerConfig,
  value: Record<string, unknown>,
  name: string
): void {
  for (const field of MCP_STRING_MAP_FIELDS) {
    if (value[field] !== undefined) {
      server[field] = requireStringMap(value[field], `mcp_servers.${name}.${field}`);
    }
  }
}

function validateMcpServer(name: string, server: NativeMcpServerConfig): void {
  if (Boolean(server.command) === Boolean(server.url)) {
    throw new Error(`mcp_servers.${name} must define exactly one of command or url`);
  }

  const incompatibleFields = server.command ? MCP_HTTP_ONLY_FIELDS : MCP_STDIO_ONLY_FIELDS;
  for (const field of incompatibleFields) {
    if (server[field as keyof NativeMcpServerConfig] !== undefined) {
      const transport = server.command ? 'stdio' : 'HTTP';
      throw new Error(`mcp_servers.${name}.${field} is not valid for ${transport} transport`);
    }
  }

  if (!server.url) return;
  let parsedUrl: URL;
  try {
    parsedUrl = new URL(server.url);
  } catch {
    throw new Error(`mcp_servers.${name}.url must be a valid URL`);
  }
  if (parsedUrl.protocol !== 'http:' && parsedUrl.protocol !== 'https:') {
    throw new Error(`mcp_servers.${name}.url must use http or https`);
  }
}

function parseMcpServer(name: string, value: unknown): NativeMcpServerConfig {
  if (!isRecord(value)) throw new Error(`mcp_servers.${name} must be an object`);
  const unknownFields = Object.keys(value).filter((field) => !MCP_SUPPORTED_FIELDS.has(field));
  if (unknownFields.length > 0) {
    throw new Error(`Unsupported mcp_servers.${name} fields: ${unknownFields.sort().join(', ')}`);
  }

  const server: NativeMcpServerConfig = {};
  assignMcpStringFields(server, value, name);
  assignMcpBooleanFields(server, value, name);
  assignMcpNumberFields(server, value, name);
  assignMcpArrayFields(server, value, name);
  assignMcpMapFields(server, value, name);
  validateMcpServer(name, server);
  return server;
}

function resolveMcpServers(value: unknown): Record<string, NativeMcpServerConfig> | undefined {
  if (value === undefined || value === null) return undefined;
  if (!isRecord(value)) throw new Error('mcp_servers must be an object');
  return Object.fromEntries(
    Object.entries(value)
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([name, server]) => {
        if (!name.trim()) throw new Error('mcp_servers names cannot be empty');
        return [name, parseMcpServer(name, server)];
      })
  );
}

function tomlString(value: string): string {
  for (let index = 0; index < value.length; index += 1) {
    const code = value.charCodeAt(index);
    if ((code <= 0x1f && code !== 0x09 && code !== 0x0a && code !== 0x0d) || code === 0x7f) {
      throw new Error('TOML strings cannot contain forbidden control characters');
    }
    if (code >= 0xd800 && code <= 0xdbff) {
      const next = value.charCodeAt(index + 1);
      if (!(next >= 0xdc00 && next <= 0xdfff)) {
        throw new Error('TOML strings cannot contain unpaired Unicode surrogates');
      }
      index += 1;
    } else if (code >= 0xdc00 && code <= 0xdfff) {
      throw new Error('TOML strings cannot contain unpaired Unicode surrogates');
    }
  }
  return JSON.stringify(value).replace(
    /\\u([0-9a-f]{4})/g,
    (_match, hex: string) => `\\u${hex.toUpperCase()}`
  );
}

function tomlStringArray(values: string[]): string {
  return `[${values.map(tomlString).join(', ')}]`;
}

function tomlKey(value: string): string {
  return TOML_BARE_KEY_PATTERN.test(value) ? value : tomlString(value);
}

function parseTomlStringLiteral(value: string, field: string): string {
  const basicString = value.match(/^("(?:\\.|[^"\\])*")\s*(?:#.*)?$/);
  if (basicString) {
    try {
      return JSON.parse(basicString[1]) as string;
    } catch {
      throw new Error(`Invalid native agent ${field} string`);
    }
  }
  const literalString = value.match(/^'([^']*)'\s*(?:#.*)?$/);
  if (literalString) return literalString[1];
  throw new Error(`Native agent ${field} must be a single-line TOML string`);
}

interface ParsedTomlString {
  value: string;
  consumedLines: number;
}

interface ParsedTomlEscape {
  value: string;
  nextIndex: number;
}

const TOML_BASIC_ESCAPES: Readonly<Record<string, string>> = {
  b: '\b',
  t: '\t',
  n: '\n',
  f: '\f',
  r: '\r',
  '"': '"',
  '\\': '\\',
};

function assertValidTomlStringCharacter(
  character: string,
  code: number,
  field: string,
  multiline: boolean
): void {
  if ((code <= 0x1f && character !== '\t' && !(multiline && character === '\n')) || code === 0x7f) {
    throw new Error(`Invalid native agent ${field} string`);
  }
}

function parseTomlUnicodeEscape(value: string, index: number, field: string): ParsedTomlEscape {
  const marker = value[index + 1];
  const length = marker === 'u' ? 4 : 8;
  const hexadecimal = value.slice(index + 2, index + 2 + length);
  if (!new RegExp(`^[0-9A-Fa-f]{${length}}$`).test(hexadecimal)) {
    throw new Error(`Invalid native agent ${field} Unicode escape`);
  }
  const codePoint = Number.parseInt(hexadecimal, 16);
  if (codePoint > 0x10ffff || (codePoint >= 0xd800 && codePoint <= 0xdfff)) {
    throw new Error(`Invalid native agent ${field} Unicode scalar`);
  }
  return { value: String.fromCodePoint(codePoint), nextIndex: index + 1 + length };
}

function parseTomlBasicEscape(
  value: string,
  index: number,
  field: string,
  multiline: boolean
): ParsedTomlEscape {
  const escaped = value[index + 1];
  if (Object.hasOwn(TOML_BASIC_ESCAPES, escaped)) {
    return { value: TOML_BASIC_ESCAPES[escaped], nextIndex: index + 1 };
  }
  if (escaped === 'u' || escaped === 'U') return parseTomlUnicodeEscape(value, index, field);
  if (multiline && escaped === '\n') {
    let nextIndex = index + 2;
    while (nextIndex < value.length && /[ \t\n]/.test(value[nextIndex])) nextIndex += 1;
    return { value: '', nextIndex: nextIndex - 1 };
  }
  throw new Error(`Invalid native agent ${field} escape`);
}

function decodeTomlBasicString(value: string, field: string, multiline: boolean): string {
  let decoded = '';
  for (let index = 0; index < value.length; index += 1) {
    const character = value[index];
    if (character !== '\\') {
      assertValidTomlStringCharacter(character, value.charCodeAt(index), field, multiline);
      decoded += character;
      continue;
    }
    const parsed = parseTomlBasicEscape(value, index, field, multiline);
    decoded += parsed.value;
    index = parsed.nextIndex;
  }
  return decoded;
}

function validateTomlLiteralString(value: string, field: string, multiline: boolean): string {
  for (let index = 0; index < value.length; index += 1) {
    const character = value[index];
    assertValidTomlStringCharacter(character, value.charCodeAt(index), field, multiline);
  }
  return value;
}

function findMultilineTomlTerminator(
  source: string,
  delimiter: '"""' | "'''",
  field: string
): { raw: string; end: number } {
  const quote = delimiter[0];
  for (let index = 0; index < source.length; index += 1) {
    if (delimiter === '"""' && source[index] === '\\') {
      index += 1;
      continue;
    }
    if (source[index] !== quote) continue;

    let runLength = 1;
    while (source[index + runLength] === quote) runLength += 1;
    if (runLength >= 3) {
      const contentQuotes = Math.min(runLength - 3, 2);
      return {
        raw: `${source.slice(0, index)}${quote.repeat(contentQuotes)}`,
        end: index + runLength,
      };
    }
    index += runLength - 1;
  }
  throw new Error(`Unterminated native agent ${field} multiline string`);
}

function parseTomlStringExpression(source: string, field: string): ParsedTomlString {
  const multilineDelimiter = source.startsWith('"""')
    ? '"""'
    : source.startsWith("'''")
      ? "'''"
      : null;
  if (!multilineDelimiter) {
    const firstLine = source.split('\n', 1)[0];
    return { value: parseTomlStringLiteral(firstLine, field), consumedLines: 0 };
  }

  let content = source.slice(3);
  const hasTrimmedInitialNewline = content.startsWith('\n');
  if (hasTrimmedInitialNewline) content = content.slice(1);
  const parsed = findMultilineTomlTerminator(content, multilineDelimiter, field);
  const tail = content.slice(parsed.end).split('\n', 1)[0].trim();
  if (tail && !tail.startsWith('#')) {
    throw new Error(`Invalid native agent ${field} multiline string suffix`);
  }

  return {
    value:
      multilineDelimiter === '"""'
        ? decodeTomlBasicString(parsed.raw, field, true)
        : validateTomlLiteralString(parsed.raw, field, true),
    consumedLines:
      content.slice(0, parsed.end).split('\n').length - 1 + (hasTrimmedInitialNewline ? 1 : 0),
  };
}

function parseNativeAgentTopLevelStrings(toml: string): Map<string, string> {
  const values = new Map<string, string>();
  const lines = toml.replace(/^\uFEFF/, '').split(/\r?\n/);
  for (let index = 0; index < lines.length; index += 1) {
    const line = lines[index];
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    if (trimmed.startsWith('[')) break;
    const assignment = trimmed.match(/^([A-Za-z0-9_-]+)\s*=\s*(.+)$/);
    if (assignment && NATIVE_AGENT_TOP_LEVEL_STRING_FIELDS.has(assignment[1])) {
      const parsed = parseTomlStringExpression(
        [assignment[2], ...lines.slice(index + 1)].join('\n'),
        assignment[1]
      );
      values.set(assignment[1], parsed.value);
      index += parsed.consumedLines;
    }
  }
  return values;
}

/** Read the required list metadata from a standalone native agent TOML file. */
export function parseNativeAgentListMetadata(toml: string): NativeAgentListMetadata {
  const values = parseNativeAgentTopLevelStrings(toml);
  const name = values.get('name');
  const description = values.get('description');
  if (!name || !description) {
    throw new Error('Native agent TOML requires name and description');
  }
  if (!AGENT_NAME_PATTERN.test(name)) throw new Error(`Invalid native agent name: ${name}`);
  return { name, description };
}

function parseNativeReasoningEffort(value: string | undefined): NativeReasoningEffort | undefined {
  if (!value) return undefined;
  if (!REASONING_EFFORTS.has(value as NativeReasoningEffort)) {
    throw new Error(`Invalid native agent model_reasoning_effort: ${value}`);
  }
  return value as NativeReasoningEffort;
}

function parseNativeSandboxMode(value: string | undefined): NativeSandboxMode | undefined {
  if (!value) return undefined;
  if (!SAFE_SANDBOX_MODES.has(value as NativeSandboxMode)) {
    throw new Error(`Invalid native agent sandbox_mode: ${value}`);
  }
  return value as NativeSandboxMode;
}

function parseNativeSkillNames(toml: string): string[] {
  const skills: string[] = [];
  let inSkillConfig = false;
  for (const line of toml.replace(/^\uFEFF/, '').split(/\r?\n/)) {
    const trimmed = line.trim();
    if (trimmed === '[[skills.config]]') {
      inSkillConfig = true;
      continue;
    }
    if (trimmed.startsWith('[')) {
      inSkillConfig = false;
      continue;
    }
    if (!inSkillConfig || !trimmed || trimmed.startsWith('#')) continue;
    const assignment = trimmed.match(/^path\s*=\s*(.+)$/);
    if (!assignment) continue;
    const path = parseTomlStringLiteral(assignment[1], 'skills.config.path').replaceAll('\\', '/');
    const segments = path.split('/').filter(Boolean);
    const skillName = segments.at(-1) === 'SKILL.md' ? segments.at(-2) : undefined;
    if (skillName && SKILL_NAME_PATTERN.test(skillName)) skills.push(skillName);
  }
  return skills;
}

/** Read the Web/detail fields supported by the native agent compiler contract. */
export function parseNativeAgentDetailMetadata(toml: string): NativeAgentDetailMetadata {
  const values = parseNativeAgentTopLevelStrings(toml);
  const { name, description } = parseNativeAgentListMetadata(toml);
  const developerInstructions = values.get('developer_instructions');
  if (!developerInstructions) {
    throw new Error('Native agent TOML requires developer_instructions');
  }

  const modelValue = values.get('model');

  return {
    name,
    description,
    developerInstructions,
    model: modelValue ? validateModelValue(modelValue) : undefined,
    modelReasoningEffort: parseNativeReasoningEffort(values.get('model_reasoning_effort')),
    sandboxMode: parseNativeSandboxMode(values.get('sandbox_mode')),
    skills: parseNativeSkillNames(toml),
  };
}

function appendMcpScalarFields(lines: string[], server: NativeMcpServerConfig): void {
  for (const field of MCP_SCALAR_STRING_FIELDS) {
    const value = server[field];
    if (value !== undefined) lines.push(`${field} = ${tomlString(value)}`);
  }
  for (const field of MCP_BOOLEAN_FIELDS) {
    const value = server[field];
    if (value !== undefined) lines.push(`${field} = ${String(value)}`);
  }
  for (const field of MCP_NUMBER_FIELDS) {
    const value = server[field];
    if (value !== undefined) lines.push(`${field} = ${String(value)}`);
  }
  for (const field of MCP_STRING_ARRAY_FIELDS) {
    const value = server[field];
    if (value !== undefined) lines.push(`${field} = ${tomlStringArray(value)}`);
  }
}

function appendMcpMapFields(lines: string[], name: string, server: NativeMcpServerConfig): void {
  for (const field of MCP_STRING_MAP_FIELDS) {
    const value = server[field];
    if (!value) continue;
    lines.push('', `[mcp_servers.${tomlKey(name)}.${field}]`);
    for (const [key, entry] of Object.entries(value)) {
      lines.push(`${tomlKey(key)} = ${tomlString(entry)}`);
    }
  }
}

function serializeMcpServer(name: string, server: NativeMcpServerConfig): string[] {
  const lines = [`[mcp_servers.${tomlKey(name)}]`];
  appendMcpScalarFields(lines, server);
  appendMcpMapFields(lines, name, server);
  return lines;
}

export function serializeNativeAgentToml(config: NativeAgentConfig): string {
  const lines = [
    NATIVE_AGENT_GENERATED_HEADER.trimEnd(),
    `name = ${tomlString(config.name)}`,
    `description = ${tomlString(config.description)}`,
  ];
  if (config.model) lines.push(`model = ${tomlString(config.model)}`);
  if (config.model_reasoning_effort) {
    lines.push(`model_reasoning_effort = ${tomlString(config.model_reasoning_effort)}`);
  }
  if (config.sandbox_mode) lines.push(`sandbox_mode = ${tomlString(config.sandbox_mode)}`);
  lines.push(`developer_instructions = ${tomlString(config.developer_instructions)}`);

  for (const skill of config.skills?.config ?? []) {
    lines.push('', '[[skills.config]]', `path = ${tomlString(skill.path)}`);
    lines.push(`enabled = ${String(skill.enabled)}`);
  }
  for (const [name, server] of Object.entries(config.mcp_servers ?? {})) {
    lines.push('', ...serializeMcpServer(name, server));
  }
  return `${lines.join('\n')}\n`;
}

export function compileMarkdownAgent(
  markdown: string,
  options: CompileMarkdownAgentOptions = {}
): CompiledNativeAgent {
  const parsed = parseMarkdownAgent(markdown);
  if (options.sourceFilename) {
    const filenameName = basename(options.sourceFilename, '.md');
    if (filenameName !== parsed.sourceName) {
      throw new Error(
        `Agent filename/name mismatch: ${options.sourceFilename} declares ${parsed.sourceName}`
      );
    }
  }

  const skillConfig = resolveSkillConfig(parsed.metadata.skills);
  const config: NativeAgentConfig = {
    name: parsed.sourceName,
    description: parsed.description,
    developer_instructions: parsed.developerInstructions,
    model: resolveModel(parsed.metadata, options.modelLanes),
    model_reasoning_effort: resolveReasoningEffort(parsed.metadata),
    sandbox_mode: resolveSandboxMode(parsed.metadata),
    mcp_servers: resolveMcpServers(parsed.metadata.mcp_servers),
    skills: skillConfig ? { config: skillConfig } : undefined,
  };

  return {
    sourceName: parsed.sourceName,
    filename: `${parsed.sourceName}.toml`,
    domain: parsed.domain,
    config,
    toml: serializeNativeAgentToml(config),
  };
}

function isGeneratedNativeAgent(content: string): boolean {
  return content.startsWith(NATIVE_AGENT_GENERATED_HEADER);
}

async function readExistingTomlFiles(destinationDir: string): Promise<Map<string, string>> {
  const existing = new Map<string, string>();
  try {
    const entries = await readdir(destinationDir, { withFileTypes: true });
    for (const entry of entries.sort((left, right) => left.name.localeCompare(right.name))) {
      if (!entry.name.toLowerCase().endsWith('.toml')) continue;
      if (entry.isSymbolicLink()) {
        throw new Error(`Unsafe native agent destination: symbolic link ${entry.name}`);
      }
      if (!entry.isFile()) continue;
      existing.set(entry.name, await readFile(join(destinationDir, entry.name), 'utf8'));
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error;
  }
  return existing;
}

async function compileSourceDirectory(
  options: SyncNativeAgentsOptions
): Promise<{ all: CompiledNativeAgent[]; selected: CompiledNativeAgent[] }> {
  const entries = await readdir(options.sourceDir, { withFileTypes: true });
  const modelLanes = options.modelLanes ?? getConfiguredModelLanes();
  const all: CompiledNativeAgent[] = [];
  for (const entry of entries.sort((left, right) => left.name.localeCompare(right.name))) {
    if (!entry.name.endsWith('.md')) continue;
    if (entry.isSymbolicLink()) {
      throw new Error(`Unsafe managed agent source: symbolic link ${entry.name}`);
    }
    if (!entry.isFile()) continue;
    const markdown = await readFile(join(options.sourceDir, entry.name), 'utf8');
    const agent = compileMarkdownAgent(markdown, {
      sourceFilename: entry.name,
      modelLanes,
    });
    all.push(agent);
  }
  return {
    all,
    selected: all.filter((agent) => shouldInstallAgent(agent.domain, options.domain)),
  };
}

interface NativeAgentSyncPlan {
  desired: Map<string, CompiledNativeAgent>;
  written: string[];
  unchanged: string[];
  removed: string[];
  preserved: string[];
  filtered: string[];
}

function assertNoCaseFoldCollisions(
  compiled: CompiledNativeAgent[],
  existing: Map<string, string>
): void {
  const compiledByFold = new Map<string, string>();
  for (const agent of compiled) {
    const folded = agent.filename.toLowerCase();
    const conflicting = compiledByFold.get(folded);
    if (conflicting) {
      throw new Error(
        `Managed agent sources have a case-insensitive filename collision: ${conflicting}, ${agent.filename}`
      );
    }
    compiledByFold.set(folded, agent.filename);
  }

  const existingByFold = new Map<string, string>();
  for (const filename of existing.keys()) {
    const folded = filename.toLowerCase();
    const conflicting = existingByFold.get(folded);
    if (conflicting) {
      throw new Error(
        `Native agent destination has a case-insensitive filename collision: ${conflicting}, ${filename}`
      );
    }
    existingByFold.set(folded, filename);

    const compiledFilename = compiledByFold.get(folded);
    if (compiledFilename && compiledFilename !== filename) {
      throw new Error(
        `Native agent filename collides case-insensitively with managed role: ${filename}, ${compiledFilename}`
      );
    }
  }
}

function createNativeAgentSyncPlan(
  compiled: CompiledNativeAgent[],
  allCompiled: CompiledNativeAgent[],
  existing: Map<string, string>
): NativeAgentSyncPlan {
  assertNoCaseFoldCollisions(allCompiled, existing);
  const desired = new Map(compiled.map((agent) => [agent.filename, agent]));
  if (desired.size !== compiled.length) {
    throw new Error('Managed agent sources compile to duplicate native role filenames');
  }
  const allManagedFilenames = new Set(allCompiled.map((agent) => agent.filename));

  const written: string[] = [];
  const unchanged: string[] = [];
  const removed: string[] = [];
  const preserved: string[] = [];
  const filtered: string[] = [];
  for (const [filename, content] of existing) {
    if (!isGeneratedNativeAgent(content)) {
      preserved.push(filename);
      desired.delete(filename);
      continue;
    }
    const agent = desired.get(filename);
    if (agent?.toml === content) {
      unchanged.push(filename);
      desired.delete(filename);
    } else if (!agent) {
      if (allManagedFilenames.has(filename)) filtered.push(filename);
      else removed.push(filename);
    }
  }

  written.push(...desired.keys());
  for (const entries of [written, unchanged, removed, preserved, filtered]) entries.sort();
  return { desired, written, unchanged, removed, preserved, filtered };
}

async function prevalidateNativeAgentSyncPlan(
  options: SyncNativeAgentsOptions,
  plan: NativeAgentSyncPlan
): Promise<void> {
  for (const filename of plan.written) {
    await prevalidateSafeWritePath(join(options.destinationDir, filename), options.targetRoot);
  }
  for (const filename of plan.removed) {
    const path = join(options.destinationDir, filename);
    const stats = await lstat(path);
    if (stats.nlink > 1) {
      throw new Error(`Unsafe native agent deletion: hard-linked file ${filename}`);
    }
    await validateSafeDeleteFilePath(path, options.targetRoot);
  }
}

async function prepareNativeAgentSync(
  options: SyncNativeAgentsOptions
): Promise<{ compiled: CompiledNativeAgent[]; plan: NativeAgentSyncPlan }> {
  await prevalidateSafeWritePath(
    join(options.destinationDir, '.omcodex-native-agent-probe'),
    options.targetRoot
  );
  const compiled = await compileSourceDirectory(options);
  const existing = await readExistingTomlFiles(options.destinationDir);
  const plan = createNativeAgentSyncPlan(compiled.selected, compiled.all, existing);
  await prevalidateNativeAgentSyncPlan(options, plan);
  return { compiled: compiled.selected, plan };
}

/** Validate a managed native-agent sync without mutating the destination. */
export async function prevalidateNativeAgentSync(options: SyncNativeAgentsOptions): Promise<void> {
  await prepareNativeAgentSync(options);
}

async function applyNativeAgentSync(
  options: SyncNativeAgentsOptions,
  plan: NativeAgentSyncPlan
): Promise<void> {
  for (const filename of plan.written) {
    const agent = plan.desired.get(filename);
    if (!agent) throw new Error(`Missing compiled native agent for ${filename}`);
    await writeTextFile(join(options.destinationDir, filename), agent.toml, {
      trustedWriteRoot: options.targetRoot,
    });
  }
  for (const filename of plan.removed) {
    await deleteFile(join(options.destinationDir, filename), options.targetRoot);
  }
}

/**
 * Safely regenerate managed native agents while preserving custom TOML roles.
 *
 * Only files carrying NATIVE_AGENT_GENERATED_HEADER are overwritten or removed.
 * A custom file with the same role name wins and is returned in `preserved`.
 */
export async function syncNativeAgents(
  options: SyncNativeAgentsOptions
): Promise<SyncNativeAgentsResult> {
  const { compiled, plan } = await prepareNativeAgentSync(options);
  await applyNativeAgentSync(options, plan);
  return {
    compiled,
    written: plan.written,
    unchanged: plan.unchanged,
    removed: plan.removed,
    preserved: plan.preserved,
    filtered: plan.filtered,
  };
}
